import { computed } from 'vue'

import { findLineStation, getLineAllStations } from '../engine/network/geometry'
import { createPassengerJourneyPlanner, planPassengerJourney } from '../engine/passengers'
import { stationDistanceMeters } from '../engine/transitRuntime'
import type { GamePassengerJourneyPlan } from '../types/passengers'
import type { GameWalkingTransfer } from '../types/network'
import { useMetropoleGame } from './useMetropoleGame'
import { useGameSimulation } from './useGameSimulation'

function createTransferId() {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') return crypto.randomUUID()
  return `walk-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`
}

function clampWalkingMinutes(value: unknown) {
  const minutes = Number(value)
  return Number.isFinite(minutes) ? Math.min(60, Math.max(1, Math.round(minutes))) : 5
}

function transferPairKey(item: Pick<GameWalkingTransfer, 'fromLineId' | 'fromStationId' | 'toLineId' | 'toStationId'>) {
  const a = `${item.fromLineId}:${item.fromStationId}`
  const b = `${item.toLineId}:${item.toStationId}`
  return a < b ? `${a}|${b}` : `${b}|${a}`
}

export function useGamePassengers() {
  const game = useMetropoleGame()
  const simulation = useGameSimulation()

  const state = computed(() => game.state.value.save?.data.passengers ?? null)
  const walkingTransfers = computed(() => game.state.value.save?.data.network.walkingTransfers ?? [])
  const lastReport = computed(() => state.value?.lastReport ?? null)

  function assertWritable() {
    if (game.isReadOnly.value) throw new Error('Ce défi est terminé : la partie est en lecture seule.')
  }

  function resolvePlatform(lineId: string, stationId: string) {
    const save = game.state.value.save
    const line = save?.data.network.lines.find(item => item.id === lineId)
    const station = line ? findLineStation(line, stationId) : null
    return line && station ? { line, station } : null
  }

  async function createWalkingTransfer(
    fromLineId: string,
    fromStationId: string,
    toLineId: string,
    toStationId: string,
    walkingMinutes: number,
  ) {
    assertWritable()
    const save = game.state.value.save
    if (!save) throw new Error('Aucune partie chargée.')
    const from = resolvePlatform(fromLineId, fromStationId)
    const to = resolvePlatform(toLineId, toStationId)
    if (!from || !to) throw new Error('Sélectionnez deux stations valides.')
    if (from.line.id === to.line.id && from.station.id === to.station.id) throw new Error('Choisissez deux stations différentes.')
    if (from.line.id !== to.line.id && from.station.sharedStationId && from.station.sharedStationId === to.station.sharedStationId) {
      throw new Error('Ces stations sont déjà une correspondance physique.')
    }

    const candidate = {
      fromLineId: from.line.id,
      fromStationId: from.station.id,
      toLineId: to.line.id,
      toStationId: to.station.id,
    }
    const key = transferPairKey(candidate)
    if ((save.data.network.walkingTransfers ?? []).some(item => transferPairKey(item) === key)) {
      throw new Error('Cette correspondance existe déjà.')
    }

    const now = new Date().toISOString()
    const transfer: GameWalkingTransfer = {
      id: createTransferId(),
      autoGenerated: false,
      ...candidate,
      walkingMinutes: clampWalkingMinutes(walkingMinutes),
      distanceMeters: Math.round(stationDistanceMeters(from.station, to.station)),
      createdAt: now,
      updatedAt: now,
    }
    save.data.network.walkingTransfers = [...(save.data.network.walkingTransfers ?? []), transfer]
    save.data.passengers.lastReport = null
    await game.persistCurrentGame()
    return transfer
  }

  async function updateWalkingTransfer(id: string, walkingMinutes: number) {
    assertWritable()
    const save = game.state.value.save
    if (!save) return false
    const transfer = (save.data.network.walkingTransfers ?? []).find(item => item.id === id)
    if (!transfer) return false
    transfer.walkingMinutes = clampWalkingMinutes(walkingMinutes)
    // Dès que le joueur personnalise la durée, la liaison devient manuelle :
    // les prochains déplacements de station ne doivent plus l'écraser.
    transfer.autoGenerated = false
    const from = resolvePlatform(transfer.fromLineId, transfer.fromStationId)
    const to = resolvePlatform(transfer.toLineId, transfer.toStationId)
    if (from && to) transfer.distanceMeters = Math.round(stationDistanceMeters(from.station, to.station))
    transfer.updatedAt = new Date().toISOString()
    save.data.passengers.lastReport = null
    await game.persistCurrentGame()
    return true
  }

  async function deleteWalkingTransfer(id: string) {
    assertWritable()
    const save = game.state.value.save
    if (!save) return false
    const before = (save.data.network.walkingTransfers ?? []).length
    save.data.network.walkingTransfers = (save.data.network.walkingTransfers ?? []).filter(item => item.id !== id)
    if (save.data.network.walkingTransfers.length === before) return false
    save.data.passengers.lastReport = null
    await game.persistCurrentGame()
    return true
  }

  function createJourneyPreview() {
    const save = game.state.value.save
    if (!save) return null
    return createPassengerJourneyPlanner({
      network: save.data.network,
      day: simulation.day.value,
      calendarStartDate: save.data.calendarStartDate,
      operations: save.data.operations,
      lineReports: simulation.lastDayReport.value?.lines ?? [],
    })
  }

  function previewJourney(
    originLineId: string,
    originStationId: string,
    destinationLineId: string,
    destinationStationId: string,
    departureMinute: number,
  ): GamePassengerJourneyPlan | null {
    const save = game.state.value.save
    if (!save) return null
    return planPassengerJourney(
      {
        network: save.data.network,
        day: simulation.day.value,
        calendarStartDate: save.data.calendarStartDate,
        operations: save.data.operations,
        lineReports: simulation.lastDayReport.value?.lines ?? [],
      },
      originLineId,
      originStationId,
      destinationLineId,
      destinationStationId,
      Math.min(1439, Math.max(0, Math.round(Number(departureMinute) || 0))),
    )
  }

  function stationsForLine(lineId: string) {
    const save = game.state.value.save
    const line = save?.data.network.lines.find(item => item.id === lineId)
    return line ? getLineAllStations(line) : []
  }

  return {
    state,
    walkingTransfers,
    lastReport,
    stationsForLine,
    createWalkingTransfer,
    updateWalkingTransfer,
    deleteWalkingTransfer,
    previewJourney,
    createJourneyPreview,
  }
}
