export type GameTransportMode =
  | 'METRO'
  | 'TRAM'
  | 'RER'
  | 'TRAIN'
  | 'BUS'
  | 'BRT'
  | 'CABLE'
  | 'FERRY'

export type GameServiceLevel =
  | 'REDUCED'
  | 'STANDARD'
  | 'FREQUENT'
  | 'INTENSIVE'

export type GameServicePeriod =
  | 'OFF_PEAK'
  | 'NORMAL'
  | 'PEAK'

export type GameServiceProfileMode =
  | 'SIMPLE'
  | 'ADVANCED'

export interface GameServiceProfile {
  offPeak: GameServiceLevel
  normal: GameServiceLevel
  peak: GameServiceLevel
}


export type GameScheduleMode =
  | 'FREQUENCY'
  | 'TIMETABLE'

export type GameServiceDayType =
  | 'WEEKDAY'
  | 'SATURDAY'
  | 'SUNDAY'

export interface GameMissionDepartures {
  weekday: number[]
  saturday: number[]
  sunday: number[]
}

export interface GameLineMission {
  id: string
  /** Code court affiché sur les prochains passages : KALI, PAUL, M01... */
  code: string
  name: string
  enabled: boolean
  /** Parcours exact de la mission, dans l'ordre de circulation. */
  routeStationIds: string[]
  /** Sous-ensemble des stations réellement desservies. Les deux terminus restent toujours desservis. */
  stopStationIds: string[]
  /** Temps d'arrêt commercial moyen appliqué aux arrêts intermédiaires. */
  dwellMinutes: number
  /** Départs, en minutes depuis 00:00, séparés par type de journée. */
  departures: GameMissionDepartures
}

export interface GameLineSchedule {
  mode: GameScheduleMode
  missions: GameLineMission[]
}

export type GameMaintenanceLevel =
  | 'ECONOMY'
  | 'STANDARD'
  | 'PREVENTIVE'

export type GameRegulationMode =
  | 'AUTO'
  | 'MANUAL'

export type GameRollingStockUpgradeKey =
  | 'capacity'
  | 'speed'
  | 'reliability'
  | 'efficiency'
  | 'boarding'

export interface GameRollingStockUpgrades {
  capacity: number
  speed: number
  reliability: number
  efficiency: number
  boarding: number
}

export type GameInspectionMode =
  | 'AUTO'
  | 'CUSTOM'

export type GameStationFacilityLevel =
  | 'BASIC'
  | 'STANDARD'
  | 'HUB'

export type GameLineStatus =
  | 'PROJECT'
  | 'CONSTRUCTION'
  | 'OPERATIONAL'

export type GameLineBadgeStyle =
  | 'CIRCLE'
  | 'ROUNDED'
  | 'SQUARE'
  | 'DIAMOND'

export type GameLineEmblem =
  | 'NONE'
  | 'METRO'
  | 'TRAM'
  | 'RER'
  | 'TRAIN'
  | 'BUS'
  | 'EXPRESS'
  | 'CABLE'
  | 'FERRY'
  | 'STAR'

export type GameLineRoutingMode =
  | 'ASSISTED'
  | 'LIGHT'
  | 'FREE'

export interface GameLineRouteSegment {
  fromStationId: string
  toStationId: string
  /** Géométrie visuelle persistée entre les deux stations, extrémités incluses. */
  coordinates: Array<[number, number]>
  source: 'ASSISTED' | 'FREE'
}

export type GameInfrastructureUpgradeKey =
  | 'capacity'
  | 'speed'
  | 'reliability'

export interface GameInfrastructureSegmentState {
  fromStationId: string
  toStationId: string
  capacityLevel: number
  speedLevel: number
  reliabilityLevel: number
}

export type GameInfrastructureType =
  | 'AUTO'
  | 'SURFACE'
  | 'TUNNEL'
  | 'VIADUCT'
  | 'DEDICATED'
  | 'ROAD'
  | 'RAIL'
  | 'CABLE'
  | 'WATER'

export interface GameStation {
  id: string
  name: string
  longitude: number
  latitude: number
  facilityLevel?: GameStationFacilityLevel
  /** Identifiant partagé quand plusieurs lignes utilisent physiquement la même station. */
  sharedStationId?: string
}

export interface GameLineBranch {
  id: string
  /** Station existante où la branche quitte le tracé principal ou une autre branche. */
  fromStationId: string
  /** Stations propres à la branche, sans dupliquer la station de bifurcation. */
  stations: GameStation[]
}

export interface GameWalkingTransfer {
  id: string
  /** Liaison créée automatiquement lors de la construction d'une station proche. */
  autoGenerated?: boolean
  fromLineId: string
  fromStationId: string
  toLineId: string
  toStationId: string
  walkingMinutes: number
  distanceMeters: number
  createdAt: string
  updatedAt: string
}


export interface GameDepot {
  id: string
  name: string
  mode: GameTransportMode
  longitude: number
  latitude: number
  /** Capacité maximale de remisage, tous véhicules des lignes affectées confondus. */
  capacity: number
  createdAt: string
  updatedAt: string
}

export interface GameInterchangeLink {
  fromLineId: string
  fromStationId: string
  toLineId: string
  toStationId: string
  distanceMeters: number
  walkingMinutes: number
  kind: 'PHYSICAL' | 'WALKING'
  manualLinkId?: string
  quality: 'DIRECT' | 'GOOD' | 'LONG' | 'VERY_LONG'
}

export interface GameLine {
  id: string
  name: string
  /** Logo local compressé (data URL) choisi par le joueur. */
  customLogoDataUrl?: string
  /** Indice court affiché dans le badge de ligne : 1, A, T3, N... */
  shortCode: string
  badgeStyle: GameLineBadgeStyle
  emblem: GameLineEmblem
  mode: GameTransportMode
  status: GameLineStatus
  infrastructureType: GameInfrastructureType
  /** V35 : l'assistance de tracé reste désactivable à tout moment par le joueur. */
  routingMode?: GameLineRoutingMode
  /** Géométrie intermédiaire invisible : elle ne crée aucune station supplémentaire. */
  routeSegments?: GameLineRouteSegment[]
  serviceLevel: GameServiceLevel
  serviceProfileMode: GameServiceProfileMode
  serviceProfile: GameServiceProfile
  /** V46 : horaires manuels. FREQUENCY conserve le système historique. */
  schedule?: GameLineSchedule
  maintenanceLevel: GameMaintenanceLevel
  fleetCondition: number
  vehicleCount: number
  /** V51 : modèle principal exploité sur la ligne. */
  rollingStockModelId?: string
  /** V51 : dépôt principal. Une ligne héritée peut rester sans dépôt. */
  depotId?: string
  /** Phase 25 : modernisations persistées par tronçon. Les tronçons absents restent au niveau 0. */
  infrastructureSegments?: GameInfrastructureSegmentState[]
  rollingStockUpgrades: GameRollingStockUpgrades
  regulationMode: GameRegulationMode
  /** Nombre de véhicules de réserve volontairement injectés en manuel. */
  manualBoostVehicles: number
  inspectionMode: GameInspectionMode
  controllerCount: number
  color: string
  createdAt: string
  updatedAt: string
  constructionCost: number
  estimatedConstructionCost: number
  constructionDaysRemaining: number
  stations: GameStation[]
  /** Branches persistées. Le tronc principal reste dans `stations`. */
  branches?: GameLineBranch[]
}

export interface GameNetworkState {
  lines: GameLine[]
  /** V49 : correspondances piétonnes créées manuellement entre deux stations distinctes. */
  walkingTransfers?: GameWalkingTransfer[]
  /** V51 : dépôts de matériel roulant créés par le joueur. */
  depots?: GameDepot[]
}
